# Generated by Django 2.2.9 on 2020-01-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=225)),
                ('publication', models.CharField(max_length=225)),
                ('audio_file', models.FileField(upload_to='audios/')),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('price', models.CharField(help_text='In rupees', max_length=100)),
            ],
        ),
    ]
