# Generated by Django 2.2.6 on 2020-01-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='audios/image'),
        ),
    ]
